# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GEOF211 resource pages
author: Teachers in GEOF211
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: GEOF211book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
 - GEOF211.bib

# Information about where the book exists on the web
repository:
  url: https://kjerstid.github.io/GEOF211_compendium/intro.html  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

#Add launch button for binder to use interactive coding
launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)

#Add launch button for Thebe to run interactive code
launch_buttons:
  thebe                  : true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

